apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: petclinic-gateway-cert
  namespace: default
spec:
  dnsNames:
  - petclinic.taplab.tap.fynesy.com
  secretName: tapfynesycom
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
